### ISSUE TITLE
Gerrit Hooks Error In Windows

### ISSUE THREAD

**Issue by scm20008** [GerritCodeReview/gerrit#2]
I have a problem about the ref-update hook for gerrit in windows server 2008/2012.

I have a ref-update.bat hook, and in ref-update.bak I call/run the python script, then it disappears an error when I push changes to gerrit.
the python script can be run, because I can get the log from the python script.

If I don't call/run python script or others scripts, the ref-update.bak works. why?
Tips: the gerrit version is 2.13, my email: hbingbing@foxmail.com

Could anyone help me? thanks.

![2017-07-21_111457](https://user-images.githubusercontent.com/639305/28447831-f646d996-6e05-11e7-9873-0d1a6cf282ab.jpg)

**Comment by lucamilanesio** [comment]
Dear @scm20008, the GitHub repos are simply a mirror of the main project on gerrit-review.googlesource.com. For issues, questions or any other feedback, please  refer to:
- issues => https://www.gerritcodereview.com/issues.md
- mailing list => https://groups.google.com/forum/#!forum/repo-discuss

For any other info, see the Gerrit Code Review homepage at www.gerritcodereview.com
